### ISSUE TITLE
new ust xml url?

### ISSUE THREAD

**Issue by liyi-1989** [epogrebnyak/ust#1]
https://github.com/epogrebnyak/data-ust/blob/d76f9c51c11be0ec6cc889e42c0d1a655fca1043/ust.py#L27-L29

Maybe sth like:

```
https://home.treasury.gov/resource-center/data-chart-center/interest-rates/pages/xml?data=daily_treasury_yield_curve&field_tdr_date_value={}".format(year)
```

given the update:

https://home.treasury.gov/developer-notice-xml-changes

**Comment by epogrebnyak** [comment]
Seems old links still work, but will change in fue process, thanks for pointing.

**Comment by liyi-1989** [comment]
yeah, the old link works but the data stops at 2/18/2022 I believe. Thanks!

**Comment by epogrebnyak** [comment]
Noted, thanks

ср, 9 мар. 2022 г., 17:44 Yi Li ***@***.***>:
